services:
  backend:
    build: ./tour-backend
    container_name: tour_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./tour-backend/.env

  frontend:
    build: ./tours_app
    container_name: tour_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./tours_app/.env